---
title: "Homework1"
subtitle: BIOS6643 Fall 2021
date: "8/20/2021"
output:
  # html_document:
  #   df_print: paged
  pdf_document:
    latex_engine: xelatex
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(emo)
```

# Question 1 PCA 

Consider the eNO data, and how we applied PCA to the data for graphical purposes (see Graphs slides).  Determine the slope of the regression of Post ($Y_2$) on Pre ($Y_1$) values (i.e., a standard 'baseline as covariate' model), and compare this to the 'slope' of the $PC1$ axis.  Compare the slopes numerically and superimpose the lines on a scatterplot of Post versus Pre values.  


In order to do this, recall $PC1 = a Y_1 + b Y_2$, where a and b are chosen to maximize the variance of $PC1$ (recall $a=0.51$, $b=0.86$ for the data; see the slides).  


Note:  in terms of $Y_2$ versus $Y_1$, the 'slope' of the $PC1$ axis is simply $b/a$; to create a line to graph for $PC1$, you can have it go through the joint sample mean of $Y_1$ and $Y_2$.  This exercise helps demonstrate the 'regression' principle in a regression line.

\newpage

# Question 2 GLM, GzLM, and LMM

In a paragraph, explain the difference between a general linear model (GLM; not a generalized linear model, which I denote with GzLM and which will be discussed more later) and a linear mixed model (LMM).

\newpage

# Question 3 Profiled likelihood, restricted likelihood, and Likelihood functions

In a short paragraph, explain the difference between a profiled likelihood and a restricted likelihood for a linear mixed model, and how and why they are used.  Which one is a re-expression of the standard likelihood?

\newpage

# Question 4 Variance in LMM

Derive $Var[\pmb {\hat \beta}]$ in a full-rank linear mixed model, given the algebraic form of $\pmb {\hat \beta}$  that is obtained via ML estimation.  

NOTE:  there are two types of variance, model-based and empirical (or sandwich estimator `r emo::ji("sandwich")`).  The difference is whether the middle $\pmb V$ is determined via the model or using squared residual quantities; derive _the model-based form_.  To answer this question, work with the 'complete data' form of $\pmb {\hat \beta}$.












