---
title: 'BIOS 6612 HW 5: Linear Mixed Models'
header-includes:
  - \usepackage{multirow}
output:
  pdf_document: default
urlcolor: blue
---

```{r, include=F}
library(knitr)
library(ggplot2)
opts_chunk$set(tidy = F)
```

In a study of exercise therapies, 37 patients were assigned to one of two weightlifting programs.  In the first program (treatment 1), the number of repetitions was increased as subjects became stronger.  In the second program (treatment 2), the number of repetitions was fixed but the amount of weight was increased as a subject became stronger.  Measures of strength were taken at baseline (day 0), and on days 2,4,6,8,10, and 12.  

The raw data are stored in an external file: `exercise_therapy.dat`

Each row of the data set contains the following variables: 

* `id`: the subject identifier 
* `time`: time in days
* `trt`: a categorical variable coded 1 = Program 1 (increased number of repetitions), 2 = Program 2 (increased amount of weight)
* `y`: the outcome, a measure of strength 


## Exercise 1: EDA (20 points)

Perform exploratory data analysis to better understand the impact of the two weigthlifting programs on strength over time.


**1a. (10 pts)** Construct spaghetti plots that display the strength versus time (in days) for each of the two treatment groups. Interpret trends that you see.


**1b. (5 pts)** Construct a plot of the smoothed means for the two groups (on one plot). Interpret trends that you see.


**1c. (5 pts)** From the plots do you see evidence that a random intercept should be included in a model? A random slope?

 
## Exercise 2: Random Intercept Model  (60 points)

**2a. (10 pts)** Write out the notation and assumptions for a model with a randomly varying intercept for subject. Include in your model (1) treatment, (2) a linear time trend, and (3) a treatment by linear time trend interaction.



**2b.(5 pts)** In this model, which are the fixed effects and which are the random effects?



**2c. (10 pts)**  Fit this model in R. As output, provide table of fixed effects with estimate, Std. Error, and t value, and table of random effects variance estimates.


**2d. (10 pts)** What is the estimated variance of the random intercepts? Calculate and interpret the ICC for this model.


**2e. (10 pts)** Test the significance of the fixed effects in the model. Interpret each of the fixed effects.

**2f. (10 pts)** Test the significance of the random intercept term.

**2g. (5 pts)** Based on the analysis up to this point, interpret the effect of treatment on changes in strength. Does your analysis suggest a difference between the two groups?



## Exercise 3: Random Slope Model  (20 points)


**3a. (15 pts)** Refit a model that includes a random slope. What is the estimated variance of the random intercept in this model? What is the estimated variance of the random slope in this model? What is the correlation between the random intercept and slope in this model?


**3b. (5 pts)** Is a model with only randomly varying intercept defensible? Explain why or why not?



